"""add sessions table

Revision ID: 3ee15b8edebb
Revises: feac35539764
Create Date: 2018-08-03 23:32:03.940252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ee15b8edebb'
down_revision = 'feac35539764'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
        sa.Column('id', sa.String(length=32), nullable=False),
        sa.Column('data', sa.String(length=262144), nullable=False),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    # ### end Alembic commands ###
